name: Upload at Firebase App Distribution
on:
  push:
    branches:
      - main
jobs:
  generate-apk:
    name: ️Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Build debug apk
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload debug apk
        uses: actions/upload-artifact@v1
        with:
          name: JustMusic
          path: app/build/outputs/apk/debug/app-debug.apk

  firebase-deploy:
    name: Deploy to Firebase App Distribution
    needs: [ generate-apk ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: JustMusic

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.5
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: JustMusic/app-debug.apk